version: '3.8'
services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    ports:
      - "3306:3306"

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    restart: unless-stopped

volumes:
  WordPress: {}
  DB: {}

networks:
  inception: {}
