version: '3.8'
services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - WP:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file:
      - .env
    volumes:
      - WP:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  WP:
    driver: local
    name: WP
    driver_opts:
      type: none
      device: /Users/gkehren/data/www
      o: bind
  DB:
    driver: local
    name: DB
    driver_opts:
      type: none
      device: /Users/gkehren/data/db
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
