version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    volumes:
      - DB:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - WP:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file:
      - .env
    volumes:
      - WP:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  WP:
    driver: local
    driver_opts:
      type: volume
      device: ${WP_PATH}
      o: bind
  DB:
    driver: local
    driver_opts:
      type: volume
      device: ${DB_PATH}
      o: bind

networks:
  inception:
